### ISSUE TITLE
Error with certain models - Cannot read property 'camserv' of undefined

### ISSUE THREAD

**Issue by abcminer** [ZombieAlex/MFCAuto#12] opened 2017-07-22 02:05 UTC
Getting this error with master
(node:32223) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'camserv' of undefined
Guessing MFC changed something again

**Comment by ZombieAlex** [comment] 2017-07-22 03:15
MFCAuto doesn't reference "camserv" anywhere aside from an interface definition in sMessages.ts, which could not cause this.

I'd have to see your code to know what's causing this, but if it was working before and broke when you pulled the latest master, then I suspect you might need to update your code to account for breaking changes in MFCAuto v4 135645450bc4b77f180b4b34dcadb61beb858de9

You could try downgrading to MFCAuto v3.4.6, 6dadf17b81a85a74cb7171edbacd41dc6fa647e8, and see if the issue goes away.

If you're installing via NPM, that would be:

```bash
$ npm install ZombieAlex/MFCAuto#v3.4.6
```

**Comment by abcminer** [comment] 2017-07-22 16:02
So I was running an older version of MFCAuto when it first broke, but when I look at the raw output, the outputted json from the server request doesn't have the camserv for certain models. I've seen this with 
 models: jett_meow, bambiii_babe, illicit69
All other models, the code works fine, but for whatever reason, however whatever code probes the MFC servers, it doesn't return their information. Just returns as if they were offline. I've tried a number of different versions of MFCAuto and all the same output. This seemed to stop working in the past week. Worked before that.

**Comment by abcminer** [comment] 2017-07-22 16:08
Code is straight-forward:

"use strict";
let assert = require("assert");
var mfc = require("MFCAuto");
var client = new mfc.Client();
var targetUsername =  process.argv[2];
var modelData = "";
client.connect(false)
    .then(() => client.queryUser(targetUsername))
    .then((rawHTML) => {
        if ( rawHTML == null) {
                console.log("Invalid");
                client.disconnect();
        }
        rawHTML = JSON.stringify(rawHTML);
        var modelsData = JSON.parse(rawHTML);
        if (modelsData.sid == "0") {
                console.log("Offline");
                client.disconnect();
        }
        console.log("http://video" + (modelsData.u.camserv-500) + ".myfreecams.com:1935/NxServer/ngrp:mfc_" + (100000000+modelsData.uid) + ".f4v_mobile/playlist.m3u8");
        client.disconnect();
    });

**Comment by ZombieAlex** [comment] 2017-07-22 16:25
Thanks for the extra details. That code would throw the error you mentioned if the model you queried for was offline.  For offline models, MFC just returns a minimal user object saying as such and doesn't send the "u" property bag.  As far as I can recall, it's always been like that.

If you're certain you're querying for online models and hitting this, then I'd have to look some more. But queryUser is pretty straightforward from MFCAuto's side, and if the server decides to stop sending that property then there may not be much I could do.

As an aside, queryUser resolves with only one of two types: `undefined`, or a [full Message object](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/sMessages.ts#L84). There shouldn't be any need to stringify and parse it again.

**Comment by abcminer** [comment] 2017-07-23 01:57
The codes a bit rough, but gets the job done for what I'm using it for. As far as the model response. I ended up using the MFCAuto library because other libraries were having similar consequences. Certain online models would always return an offline return message, while the MFCAuto library correctly returned their information. That was up until this past week when MFCAuto also now treated certain online models, offline. Not sure what makes these models special from the MFC Server perspective.

**Comment by ZombieAlex** [comment] 2017-07-23 03:03
It would be helpful to see exactly what queryUser is resolving with for those models when they are online. Just stringify and print the response.

It's possible the response is corrupt and that might be something I could fix.  However if the response is well-formed and says the model is offline, then that would indicate a new server bug. And I wouldn't be shocked by that. I've seen some strange things from all their recent changes.

queryUser is very literally doing the exact same thing the website does when you type a model's name into the "User Lookup" link at the bottom of your "Online Friends" list. So you should be able to reproduce any server-side issue in a browser.

However, even if queryUser can't, MFCAuto should still be able to tell you the complete state of a model and all her properties if you let it log in (even as a guest) and instead of polling for model status via queryUser, listen for model updates via the Model change callbacks.  Something like the following, which has the added benefit of updating model status instantly.

```javascript
const mfc = require("MFCAuto");

// Listen for changes on all models
mfc.Model.on("camserv", (model, previousCamserv, currentCamserv) => {
    mfc.log(`${model.nm}'s camserv updated to ${currentCamserv}`);
});

// Or listen for changes on just illicit69
mfc.Model.getModel(7744127).on("camserv", (model, previousCamserv, currentCamserv) => {
    mfc.log(`illicit69's camserv updated to ${currentCamserv}`);
});

let client = new mfc.Client();
client.connect(); // Leave it connected and rely on the callbacks
```

Usage like that is really the design intent of MFCAuto. Probably I could do a better job calling that out in the readme.

**Comment by ZombieAlex** [comment] 2017-08-10 05:09
Finally caught one of the three models you mentioned online, bambiii_babe, and ran a queryUser on her. I do see a camserv property and everything looks normal.  Might have been a temporary server glitch.

Are you still seeing the problem or can I close out the issue for now?

**Comment by abcminer** [comment] 2017-08-16 20:15
So running your above script with an illicit69 who is currently online gives no output waiting for the camserv output change.
Using the queryUser and outputting the rawHTML simply shows this:
{"sid":0,"uid":7744127,"nm":"illicit69","lv":4,"vs":127}
while running against all other online models will give their full json output, for ex (Shay2Blue)
{"lv":4,"nm":"Shay2Blue","pid":1,"sid":176439318,"uid":20027629,"vs":0,"u":{"avatar":1,"blurb":"THANKIESSSS HAHA","camserv":1340,"chat_color":"FF1CAE","chat_font":2,"chat_opt":1,"city":"Antananarivo","country":"Madagascar","creation":1441138375,"ethnic":"No Answer","occupation":"happpyyyyyyyyynesssssssssss!!","photos":42,"profile":1},"m":{"camscore":2984.6,"continent":"EU","flags":15392,"hidecs":true,"kbit":0,"lastnews":0,"mg":0,"missmfc":0,"new_model":0,"rank":350,"rc":237,"topic":"pretty in pink :D SNAP 451 TOK,200 APPLES,50 fave song,@HT ninja=400 4 DAYS TILL THE BRTHDAY"}}

The model is 100% online, yet the library into the MFC server has an issues querying specific models. Just returns as if they were offline.

**Comment by ZombieAlex** [comment] 2017-08-16 22:37
Two more questions:

1. Are you running your scripts in the same machine that you're using to view them in the browser? If they are separate machines, it's possible that the MFCAuto machine is in a region blocked by these models. Region blocked models will always appear offline.
2. Was illicit69 on cam or just online?

Thanks for the followup.

**Comment by abcminer** [comment] 2017-08-17 14:37
I can try to see if those models were blocked by region. I'll try running from a different region (Even though the server is in the US and my viewing of the models is the same region)
As for the model online, she was on cam.

**Comment by ZombieAlex** [comment] 2017-10-20 15:41
It's been a few months. If you've ruled out region block as the reason for this behavior I can take another look. Until then, I'm closing out this old issue. Thanks.

**Closed by ZombieAlex** 2017-10-20 15:41 UTC
